"""AetherOS Nexus — Vision-Based Presence Detection & Lockdown.

Provides webcam-based presence detection, face recognition,
gesture recognition integration, and automatic lockdown mode
when unauthorized presence is detected or the operator leaves.

Architecture:
    ┌─────────────────────────────────────────────────────────────┐
    │                  VisionPipeline                             │
    │  ┌────────────┐  ┌───────────────┐  ┌──────────────────┐  │
    │  │ Camera     │→ │ Frame         │→ │ Presence         │  │
    │  │ Manager    │  │ Processor     │  │ Detector         │  │
    │  └────────────┘  └───────────────┘  └────────┬─────────┘  │
    │                                              │             │
    │  ┌────────────┐  ┌───────────────┐  ┌────────▼─────────┐  │
    │  │ Lockdown   │← │ Motion        │  │ Face             │  │
    │  │ Manager    │  │ Detector      │  │ Recognizer       │  │
    │  └────────────┘  └───────────────┘  └──────────────────┘  │
    └─────────────────────────────────────────────────────────────┘
"""
from __future__ import annotations

import asyncio
import enum
import hashlib
import json
import logging
import math
import os
import struct
import threading
import time
import uuid
from abc import ABC, abstractmethod
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Set, Tuple, Union

logger = logging.getLogger("nexus.vision")


# ═══════════════════════════════════════════════════════════════════════════
# Enums & Data Models
# ═══════════════════════════════════════════════════════════════════════════

class PresenceState(enum.Enum):
    """Current presence detection state."""
    UNKNOWN = "unknown"
    PRESENT = "present"
    ABSENT = "absent"
    UNAUTHORIZED = "unauthorized"
    MULTIPLE = "multiple"
    TRANSITIONING = "transitioning"


class LockdownLevel(enum.Enum):
    """Lockdown severity levels."""
    NONE = 0
    SOFT = 1     # Screen dim, pause non-critical operations
    MEDIUM = 2   # Lock screen, require re-authentication
    HARD = 3     # Encrypt sensitive data, disable network
    CRITICAL = 4 # Full system lockdown, alert, evidence capture


class CameraState(enum.Enum):
    """Camera hardware state."""
    DISCONNECTED = "disconnected"
    CONNECTED = "connected"
    STREAMING = "streaming"
    ERROR = "error"
    PERMISSION_DENIED = "permission_denied"


@dataclass
class BoundingBox:
    """Bounding box for detected objects/faces."""
    x: int = 0
    y: int = 0
    width: int = 0
    height: int = 0
    confidence: float = 0.0
    label: str = ""

    @property
    def center(self) -> Tuple[int, int]:
        return (self.x + self.width // 2, self.y + self.height // 2)

    @property
    def area(self) -> int:
        return self.width * self.height

    def iou(self, other: "BoundingBox") -> float:
        """Intersection over Union with another bounding box."""
        x1 = max(self.x, other.x)
        y1 = max(self.y, other.y)
        x2 = min(self.x + self.width, other.x + other.width)
        y2 = min(self.y + self.height, other.y + other.height)
        if x2 <= x1 or y2 <= y1:
            return 0.0
        intersection = (x2 - x1) * (y2 - y1)
        union = self.area + other.area - intersection
        return intersection / union if union > 0 else 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "x": self.x, "y": self.y,
            "width": self.width, "height": self.height,
            "confidence": self.confidence, "label": self.label,
        }


@dataclass
class PresenceEvent:
    """Event generated by the presence detection system."""
    event_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime = field(default_factory=datetime.utcnow)
    event_type: str = ""  # "entered", "left", "unauthorized", "face_recognized"
    state_before: PresenceState = PresenceState.UNKNOWN
    state_after: PresenceState = PresenceState.UNKNOWN
    face_count: int = 0
    recognized_users: List[str] = field(default_factory=list)
    unknown_faces: int = 0
    bounding_boxes: List[BoundingBox] = field(default_factory=list)
    frame_hash: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "event_id": self.event_id,
            "timestamp": self.timestamp.isoformat(),
            "event_type": self.event_type,
            "state_before": self.state_before.value,
            "state_after": self.state_after.value,
            "face_count": self.face_count,
            "recognized_users": self.recognized_users,
            "unknown_faces": self.unknown_faces,
            "bounding_boxes": [b.to_dict() for b in self.bounding_boxes],
            "frame_hash": self.frame_hash,
            "metadata": self.metadata,
        }


@dataclass
class FaceProfile:
    """Stored face recognition profile."""
    profile_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    user_name: str = ""
    face_encodings: List[List[float]] = field(default_factory=list)
    enrollment_count: int = 0
    created_at: datetime = field(default_factory=datetime.utcnow)
    last_seen: Optional[datetime] = None
    trust_level: int = 1  # 1-5 trust scale
    is_authorized: bool = True
    metadata: Dict[str, Any] = field(default_factory=dict)

    def add_encoding(self, encoding: List[float]) -> None:
        self.face_encodings.append(encoding)
        self.enrollment_count += 1

    def get_average_encoding(self) -> List[float]:
        if not self.face_encodings:
            return []
        dim = len(self.face_encodings[0])
        avg = [0.0] * dim
        for enc in self.face_encodings:
            for i in range(dim):
                avg[i] += enc[i]
        return [v / len(self.face_encodings) for v in avg]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "profile_id": self.profile_id,
            "user_name": self.user_name,
            "enrollment_count": self.enrollment_count,
            "created_at": self.created_at.isoformat(),
            "last_seen": self.last_seen.isoformat() if self.last_seen else None,
            "trust_level": self.trust_level,
            "is_authorized": self.is_authorized,
        }


# ═══════════════════════════════════════════════════════════════════════════
# Frame Processing
# ═══════════════════════════════════════════════════════════════════════════

class FrameProcessor:
    """Processes video frames for analysis.

    Handles frame scaling, color conversion, region-of-interest extraction,
    and frame differencing for motion detection.
    """

    def __init__(self, target_width: int = 640, target_height: int = 480):
        self.target_width = target_width
        self.target_height = target_height
        self._frame_count = 0
        self._last_frame: Optional[List[List[int]]] = None
        self._background_model: Optional[List[List[float]]] = None
        self._alpha = 0.05  # Background model learning rate

    def preprocess(self, frame: List[List[List[int]]]) -> List[List[List[int]]]:
        """Preprocess a frame for analysis (resize, normalize)."""
        self._frame_count += 1
        # In real implementation, this would use cv2.resize etc.
        # Here we work with the frame as-is for the logic layer
        return frame

    def to_grayscale(self, frame: List[List[List[int]]]) -> List[List[int]]:
        """Convert RGB frame to grayscale."""
        gray = []
        for row in frame:
            gray_row = []
            for pixel in row:
                if len(pixel) >= 3:
                    # Luminance formula
                    g = int(0.299 * pixel[0] + 0.587 * pixel[1] + 0.114 * pixel[2])
                    gray_row.append(g)
                else:
                    gray_row.append(pixel[0] if pixel else 0)
            gray.append(gray_row)
        return gray

    def compute_frame_hash(self, frame: List[List[List[int]]]) -> str:
        """Compute perceptual hash of a frame for deduplication."""
        # Simple average hash approach
        h = hashlib.sha256()
        for row in frame[:10]:  # Sample first 10 rows
            for pixel in row[:10]:
                for v in pixel:
                    h.update(struct.pack("B", v & 0xFF))
        return h.hexdigest()[:16]

    def compute_difference(self, frame1: List[List[int]], frame2: List[List[int]]) -> float:
        """Compute normalized pixel difference between two grayscale frames."""
        if not frame1 or not frame2:
            return 1.0
        total_diff = 0
        pixel_count = 0
        min_rows = min(len(frame1), len(frame2))
        for r in range(min_rows):
            min_cols = min(len(frame1[r]), len(frame2[r]))
            for c in range(min_cols):
                total_diff += abs(frame1[r][c] - frame2[r][c])
                pixel_count += 1
        return total_diff / (pixel_count * 255) if pixel_count > 0 else 0.0

    def update_background(self, gray_frame: List[List[int]]) -> None:
        """Update running background model."""
        if self._background_model is None:
            self._background_model = [[float(v) for v in row] for row in gray_frame]
            return
        for r in range(min(len(self._background_model), len(gray_frame))):
            for c in range(min(len(self._background_model[r]), len(gray_frame[r]))):
                self._background_model[r][c] = (
                    (1 - self._alpha) * self._background_model[r][c]
                    + self._alpha * gray_frame[r][c]
                )

    def get_foreground_mask(self, gray_frame: List[List[int]], threshold: int = 30) -> List[List[bool]]:
        """Get foreground mask by background subtraction."""
        if self._background_model is None:
            return [[False] * len(row) for row in gray_frame]
        mask = []
        for r in range(min(len(self._background_model), len(gray_frame))):
            row_mask = []
            for c in range(min(len(self._background_model[r]), len(gray_frame[r]))):
                diff = abs(gray_frame[r][c] - self._background_model[r][c])
                row_mask.append(diff > threshold)
            mask.append(row_mask)
        return mask

    @property
    def frame_count(self) -> int:
        return self._frame_count


# ═══════════════════════════════════════════════════════════════════════════
# Motion Detection
# ═══════════════════════════════════════════════════════════════════════════

class MotionDetector:
    """Detects and tracks motion in video frames.

    Uses frame differencing and background subtraction to identify
    moving objects and estimate motion vectors.
    """

    def __init__(
        self,
        sensitivity: float = 0.5,
        min_area_ratio: float = 0.01,
        max_still_frames: int = 30,
    ):
        self.sensitivity = max(0.1, min(sensitivity, 1.0))
        self.min_area_ratio = min_area_ratio
        self.max_still_frames = max_still_frames
        self._processor = FrameProcessor()
        self._prev_gray: Optional[List[List[int]]] = None
        self._still_frame_count = 0
        self._motion_history: deque = deque(maxlen=100)
        self._is_motion_detected = False
        self._lock = threading.Lock()

    def process_frame(self, frame: List[List[List[int]]]) -> Tuple[bool, float, List[BoundingBox]]:
        """Process a frame and detect motion.

        Returns (motion_detected, motion_level, motion_regions).
        """
        gray = self._processor.to_grayscale(frame)
        self._processor.update_background(gray)

        if self._prev_gray is None:
            self._prev_gray = gray
            return (False, 0.0, [])

        # Compute frame difference
        diff_level = self._processor.compute_difference(gray, self._prev_gray)
        threshold = (1.0 - self.sensitivity) * 0.1  # Scale threshold by sensitivity
        motion_detected = diff_level > threshold

        # Get motion regions from foreground mask
        regions = []
        if motion_detected:
            mask = self._processor.get_foreground_mask(gray)
            regions = self._find_motion_regions(mask)
            self._still_frame_count = 0
        else:
            self._still_frame_count += 1

        with self._lock:
            self._is_motion_detected = motion_detected
            self._motion_history.append({
                "timestamp": time.time(),
                "level": diff_level,
                "detected": motion_detected,
                "regions": len(regions),
            })

        self._prev_gray = gray
        return (motion_detected, diff_level, regions)

    def _find_motion_regions(self, mask: List[List[bool]]) -> List[BoundingBox]:
        """Find connected regions of motion in foreground mask."""
        if not mask or not mask[0]:
            return []

        height = len(mask)
        width = len(mask[0])
        total_pixels = height * width
        min_area = int(total_pixels * self.min_area_ratio)

        # Simple region detection: scan for clusters of True pixels
        visited = [[False] * width for _ in range(height)]
        regions = []

        for r in range(0, height, 4):  # Sample every 4th row for speed
            for c in range(0, width, 4):
                if r < len(mask) and c < len(mask[r]) and mask[r][c] and not visited[r][c]:
                    # Flood fill to find region bounds
                    min_r, max_r, min_c, max_c = r, r, c, c
                    area = 0
                    stack = [(r, c)]
                    while stack:
                        cr, cc = stack.pop()
                        if (cr < 0 or cr >= height or cc < 0 or cc >= width
                                or visited[cr][cc] or not mask[cr][cc]):
                            continue
                        visited[cr][cc] = True
                        area += 1
                        min_r = min(min_r, cr)
                        max_r = max(max_r, cr)
                        min_c = min(min_c, cc)
                        max_c = max(max_c, cc)
                        # Only explore in steps to limit complexity
                        for dr, dc in [(4, 0), (-4, 0), (0, 4), (0, -4)]:
                            stack.append((cr + dr, cc + dc))

                    if area >= min_area // 16:  # Adjusted for sampling
                        regions.append(BoundingBox(
                            x=min_c, y=min_r,
                            width=max_c - min_c, height=max_r - min_r,
                            confidence=min(1.0, area / (total_pixels * 0.1)),
                            label="motion",
                        ))

        return regions

    @property
    def is_motion_detected(self) -> bool:
        with self._lock:
            return self._is_motion_detected

    @property
    def is_scene_still(self) -> bool:
        return self._still_frame_count >= self.max_still_frames

    def get_motion_summary(self) -> Dict[str, Any]:
        with self._lock:
            recent = list(self._motion_history)
        if not recent:
            return {"avg_level": 0, "motion_ratio": 0, "samples": 0}
        avg = sum(m["level"] for m in recent) / len(recent)
        motion_count = sum(1 for m in recent if m["detected"])
        return {
            "avg_level": round(avg, 4),
            "motion_ratio": round(motion_count / len(recent), 3),
            "samples": len(recent),
            "still_frames": self._still_frame_count,
        }


# ═══════════════════════════════════════════════════════════════════════════
# Face Recognition
# ═══════════════════════════════════════════════════════════════════════════

class FaceRecognizer:
    """Face detection and recognition engine.

    Maintains a database of known face profiles and performs real-time
    face detection, encoding, and matching.

    In production this would use face_recognition/dlib or MTCNN.
    This implementation provides the architectural framework.
    """

    def __init__(
        self,
        recognition_threshold: float = 0.6,
        profiles_dir: Optional[str] = None,
        max_faces: int = 10,
    ):
        self.recognition_threshold = recognition_threshold
        self.profiles_dir = profiles_dir or os.path.expanduser("~/.aetheros/face_profiles")
        self.max_faces = max_faces
        self._profiles: Dict[str, FaceProfile] = {}
        self._detection_count = 0
        self._recognition_count = 0
        self._lock = threading.Lock()
        logger.info("FaceRecognizer initialized")

    def enroll_face(self, user_name: str, frame: List[List[List[int]]], trust_level: int = 1) -> Optional[str]:
        """Enroll a face from a video frame."""
        encodings = self._extract_encodings(frame)
        if not encodings:
            logger.warning(f"No face detected for enrollment of '{user_name}'")
            return None

        with self._lock:
            # Find existing or create new
            profile = None
            for p in self._profiles.values():
                if p.user_name == user_name:
                    profile = p
                    break
            if profile is None:
                profile = FaceProfile(user_name=user_name, trust_level=trust_level)
                self._profiles[profile.profile_id] = profile

            for enc in encodings[:1]:  # Take first face
                profile.add_encoding(enc)

            logger.info(f"Enrolled face for '{user_name}' (samples={profile.enrollment_count})")
            return profile.profile_id

    def detect_faces(self, frame: List[List[List[int]]]) -> List[BoundingBox]:
        """Detect faces in a frame. Returns bounding boxes."""
        self._detection_count += 1
        # Simulated face detection using simple heuristics
        # In production: face_recognition.face_locations() or MTCNN
        if not frame or not frame[0]:
            return []

        height = len(frame)
        width = len(frame[0]) if frame[0] else 0

        # Simulate detection based on frame characteristics
        faces = []
        # Look for skin-tone regions (simplified)
        regions = self._find_skin_regions(frame)
        for (y, x, h, w) in regions[:self.max_faces]:
            faces.append(BoundingBox(
                x=x, y=y, width=w, height=h,
                confidence=0.85, label="face",
            ))
        return faces

    def recognize_faces(self, frame: List[List[List[int]]]) -> List[Tuple[BoundingBox, Optional[str], float]]:
        """Detect and recognize faces in a frame.

        Returns list of (bounding_box, user_name_or_None, confidence).
        """
        self._recognition_count += 1
        faces = self.detect_faces(frame)
        if not faces:
            return []

        encodings = self._extract_encodings(frame)
        results = []

        for i, face_box in enumerate(faces):
            if i < len(encodings):
                enc = encodings[i]
                match_name, match_conf = self._match_encoding(enc)
                results.append((face_box, match_name, match_conf))
            else:
                results.append((face_box, None, 0.0))

        return results

    def _extract_encodings(self, frame: List[List[List[int]]]) -> List[List[float]]:
        """Extract face encodings from a frame.

        Returns list of 128-dimensional encoding vectors.
        In production: face_recognition.face_encodings()
        """
        if not frame or not frame[0]:
            return []

        # Generate deterministic encoding based on frame content
        # This simulates face encoding extraction
        height = len(frame)
        width = len(frame[0])

        encodings = []
        sample_pixels = []
        step_r = max(1, height // 8)
        step_c = max(1, width // 8)
        for r in range(0, height, step_r):
            for c in range(0, width, step_c):
                if r < len(frame) and c < len(frame[r]):
                    pixel = frame[r][c]
                    sample_pixels.extend(pixel[:3])

        if len(sample_pixels) >= 128:
            encoding = [float(v) / 255.0 for v in sample_pixels[:128]]
            encodings.append(encoding)

        return encodings

    def _match_encoding(self, encoding: List[float]) -> Tuple[Optional[str], float]:
        """Match an encoding against stored profiles."""
        best_name = None
        best_score = 0.0

        with self._lock:
            for profile in self._profiles.values():
                if not profile.is_authorized:
                    continue
                avg_enc = profile.get_average_encoding()
                if not avg_enc:
                    continue
                # Cosine similarity
                dot = sum(a * b for a, b in zip(encoding, avg_enc))
                norm_a = sum(a * a for a in encoding) ** 0.5
                norm_b = sum(b * b for b in avg_enc) ** 0.5
                if norm_a > 0 and norm_b > 0:
                    similarity = dot / (norm_a * norm_b)
                    if similarity > best_score:
                        best_score = similarity
                        best_name = profile.user_name

        if best_score >= self.recognition_threshold:
            return (best_name, best_score)
        return (None, best_score)

    def _find_skin_regions(self, frame: List[List[List[int]]]) -> List[Tuple[int, int, int, int]]:
        """Simple skin-tone region detection for face candidate areas."""
        if not frame or not frame[0]:
            return []
        height = len(frame)
        width = len(frame[0])

        # Sample grid for skin-tone pixels
        skin_pixels = []
        step = max(1, min(height, width) // 20)
        for r in range(0, height, step):
            for c in range(0, width, step):
                if r < len(frame) and c < len(frame[r]) and len(frame[r][c]) >= 3:
                    red, green, blue = frame[r][c][:3]
                    # Simple skin tone check (RGB heuristic)
                    if (red > 95 and green > 40 and blue > 20 and
                        red > green and red > blue and
                        abs(red - green) > 15 and red - blue > 15):
                        skin_pixels.append((r, c))

        if not skin_pixels:
            return []

        # Cluster skin pixels into regions (simple grid-based)
        if len(skin_pixels) > 10:
            # Take center cluster as face candidate
            avg_r = sum(p[0] for p in skin_pixels) // len(skin_pixels)
            avg_c = sum(p[1] for p in skin_pixels) // len(skin_pixels)
            face_h = max(height // 4, 50)
            face_w = max(width // 4, 50)
            return [(
                max(0, avg_r - face_h // 2),
                max(0, avg_c - face_w // 2),
                face_h, face_w,
            )]
        return []

    def get_profile(self, profile_id: str) -> Optional[FaceProfile]:
        with self._lock:
            return self._profiles.get(profile_id)

    def list_profiles(self) -> List[Dict[str, Any]]:
        with self._lock:
            return [p.to_dict() for p in self._profiles.values()]

    @property
    def stats(self) -> Dict[str, Any]:
        return {
            "enrolled_profiles": len(self._profiles),
            "total_detections": self._detection_count,
            "total_recognitions": self._recognition_count,
        }


# ═══════════════════════════════════════════════════════════════════════════
# Gesture Recognition
# ═══════════════════════════════════════════════════════════════════════════

class GestureRecognizer:
    """Recognize hand gestures for touchless system control."""

    class Gesture(enum.Enum):
        NONE = "none"
        WAVE = "wave"
        THUMBS_UP = "thumbs_up"
        THUMBS_DOWN = "thumbs_down"
        OPEN_PALM = "open_palm"
        CLOSED_FIST = "closed_fist"
        POINT = "point"
        SWIPE_LEFT = "swipe_left"
        SWIPE_RIGHT = "swipe_right"
        SWIPE_UP = "swipe_up"
        SWIPE_DOWN = "swipe_down"

    def __init__(self, sensitivity: float = 0.6):
        self.sensitivity = sensitivity
        self._gesture_history: deque = deque(maxlen=30)
        self._callbacks: Dict[str, Callable] = {}
        self._detection_count = 0

    def register_gesture_handler(self, gesture: Gesture, handler: Callable) -> None:
        self._callbacks[gesture.value] = handler

    def process_frame(self, frame: List[List[List[int]]]) -> Optional[Gesture]:
        """Process a frame for gesture detection."""
        self._detection_count += 1
        # Placeholder for real gesture detection pipeline
        # Would use MediaPipe Hands in production
        return None

    def get_gesture_history(self) -> List[Dict[str, Any]]:
        return list(self._gesture_history)

    @property
    def stats(self) -> Dict[str, Any]:
        return {"detections": self._detection_count, "registered_handlers": len(self._callbacks)}


# ═══════════════════════════════════════════════════════════════════════════
# Camera Manager
# ═══════════════════════════════════════════════════════════════════════════

class CameraManager:
    """Manages webcam hardware and frame capture.

    Handles camera initialization, frame capture, resolution management,
    and graceful hardware error recovery.
    """

    def __init__(
        self,
        camera_index: int = 0,
        width: int = 640,
        height: int = 480,
        fps: int = 30,
    ):
        self.camera_index = camera_index
        self.width = width
        self.height = height
        self.fps = fps
        self._capture = None
        self._state = CameraState.DISCONNECTED
        self._frame_count = 0
        self._last_frame_time = 0.0
        self._lock = threading.Lock()
        logger.info(f"CameraManager created for camera {camera_index} ({width}x{height}@{fps}fps)")

    def open(self) -> bool:
        """Open the camera device."""
        try:
            try:
                import cv2
                self._capture = cv2.VideoCapture(self.camera_index)
                if self._capture.isOpened():
                    self._capture.set(cv2.CAP_PROP_FRAME_WIDTH, self.width)
                    self._capture.set(cv2.CAP_PROP_FRAME_HEIGHT, self.height)
                    self._capture.set(cv2.CAP_PROP_FPS, self.fps)
                    self._state = CameraState.STREAMING
                    logger.info("Camera opened successfully via OpenCV")
                    return True
                else:
                    self._state = CameraState.ERROR
                    return False
            except ImportError:
                logger.warning("OpenCV not available, camera in simulation mode")
                self._state = CameraState.CONNECTED
                return True
        except Exception as e:
            logger.error(f"Camera open failed: {e}")
            self._state = CameraState.ERROR
            return False

    def read_frame(self) -> Optional[List[List[List[int]]]]:
        """Read a frame from the camera.

        Returns frame as 3D list [rows][cols][rgb] or None on failure.
        """
        if self._capture is not None:
            try:
                import cv2
                ret, frame = self._capture.read()
                if ret:
                    self._frame_count += 1
                    self._last_frame_time = time.time()
                    # Convert numpy to list for our pipeline
                    return frame.tolist()
            except Exception:
                pass

        # Simulation mode — generate a synthetic frame
        self._frame_count += 1
        self._last_frame_time = time.time()
        frame = []
        for r in range(self.height // 10):
            row = []
            for c in range(self.width // 10):
                # Generate varying pattern
                v = int(128 + 50 * math.sin(r * 0.1 + self._frame_count * 0.01))
                row.append([v, v + 10, v - 10])
            frame.append(row)
        return frame

    def close(self) -> None:
        """Release camera resources."""
        if self._capture is not None:
            try:
                self._capture.release()
            except Exception:
                pass
            self._capture = None
        self._state = CameraState.DISCONNECTED
        logger.info("Camera released")

    @property
    def state(self) -> CameraState:
        return self._state

    @property
    def frame_count(self) -> int:
        return self._frame_count

    @property
    def is_open(self) -> bool:
        return self._state in (CameraState.CONNECTED, CameraState.STREAMING)


# ═══════════════════════════════════════════════════════════════════════════
# Lockdown Manager
# ═══════════════════════════════════════════════════════════════════════════

class LockdownManager:
    """Manages system lockdown based on presence detection events.

    Implements graduated lockdown levels with configurable timeouts
    and automatic escalation when threats persist.

    Lockdown escalation:
        NONE → SOFT (operator absent 30s) → MEDIUM (absent 2min)
        → HARD (unauthorized detected) → CRITICAL (persistent threat)
    """

    def __init__(
        self,
        soft_timeout: float = 30.0,
        medium_timeout: float = 120.0,
        auto_escalate: bool = True,
        on_lockdown_change: Optional[Callable[[LockdownLevel, LockdownLevel], None]] = None,
    ):
        self.soft_timeout = soft_timeout
        self.medium_timeout = medium_timeout
        self.auto_escalate = auto_escalate
        self._on_change = on_lockdown_change
        self._current_level = LockdownLevel.NONE
        self._level_since: float = time.time()
        self._absence_start: Optional[float] = None
        self._threat_detected_at: Optional[float] = None
        self._history: deque = deque(maxlen=200)
        self._lock = threading.Lock()
        self._actions_log: List[Dict[str, Any]] = []
        logger.info("LockdownManager initialized")

    def on_presence_event(self, event: PresenceEvent) -> None:
        """Handle a presence event and adjust lockdown level."""
        now = time.time()

        with self._lock:
            old_level = self._current_level

            if event.state_after == PresenceState.PRESENT:
                if event.recognized_users:
                    # Known user present — can reduce lockdown
                    self._absence_start = None
                    self._threat_detected_at = None
                    if self._current_level.value <= LockdownLevel.MEDIUM.value:
                        self._set_level(LockdownLevel.NONE)
                else:
                    # Unknown face present
                    self._threat_detected_at = now
                    if self._current_level.value < LockdownLevel.HARD.value:
                        self._set_level(LockdownLevel.HARD)

            elif event.state_after == PresenceState.ABSENT:
                if self._absence_start is None:
                    self._absence_start = now
                absence_duration = now - self._absence_start
                if absence_duration >= self.medium_timeout:
                    self._set_level(LockdownLevel.MEDIUM)
                elif absence_duration >= self.soft_timeout:
                    self._set_level(LockdownLevel.SOFT)

            elif event.state_after == PresenceState.UNAUTHORIZED:
                self._threat_detected_at = now
                if self._current_level.value < LockdownLevel.CRITICAL.value:
                    self._set_level(LockdownLevel.CRITICAL)

            elif event.state_after == PresenceState.MULTIPLE:
                if event.unknown_faces > 0:
                    self._set_level(LockdownLevel.HARD)

            self._history.append({
                "timestamp": datetime.utcnow().isoformat(),
                "event_type": event.event_type,
                "level_before": old_level.name,
                "level_after": self._current_level.name,
            })

            if self._current_level != old_level and self._on_change:
                self._on_change(old_level, self._current_level)

    def _set_level(self, level: LockdownLevel) -> None:
        """Set lockdown level and execute associated actions."""
        if level == self._current_level:
            return

        old = self._current_level
        self._current_level = level
        self._level_since = time.time()

        action = {
            "timestamp": datetime.utcnow().isoformat(),
            "from_level": old.name,
            "to_level": level.name,
            "actions": [],
        }

        if level == LockdownLevel.SOFT:
            action["actions"] = ["dim_display", "pause_non_critical"]
        elif level == LockdownLevel.MEDIUM:
            action["actions"] = ["lock_screen", "require_auth", "suspend_agents"]
        elif level == LockdownLevel.HARD:
            action["actions"] = ["encrypt_sensitive_data", "disable_network_shares", "alert_admin"]
        elif level == LockdownLevel.CRITICAL:
            action["actions"] = [
                "full_lockdown", "capture_evidence", "alert_all",
                "disable_external_network", "engage_kill_switch_standby",
            ]
        elif level == LockdownLevel.NONE:
            action["actions"] = ["restore_normal_operations"]

        self._actions_log.append(action)
        logger.info(f"Lockdown level changed: {old.name} → {level.name}")

    def force_lockdown(self, level: LockdownLevel) -> None:
        """Force a specific lockdown level."""
        with self._lock:
            self._set_level(level)

    def release_lockdown(self) -> None:
        """Release all lockdown measures."""
        with self._lock:
            self._set_level(LockdownLevel.NONE)
            self._absence_start = None
            self._threat_detected_at = None

    @property
    def current_level(self) -> LockdownLevel:
        with self._lock:
            return self._current_level

    @property
    def level_duration(self) -> float:
        return time.time() - self._level_since

    def get_status(self) -> Dict[str, Any]:
        with self._lock:
            return {
                "level": self._current_level.name,
                "level_value": self._current_level.value,
                "level_duration_seconds": round(time.time() - self._level_since, 1),
                "absence_duration": round(time.time() - self._absence_start, 1) if self._absence_start else None,
                "threat_active": self._threat_detected_at is not None,
                "history_count": len(self._history),
                "actions_count": len(self._actions_log),
            }


# ═══════════════════════════════════════════════════════════════════════════
# Vision Presence Detector
# ═══════════════════════════════════════════════════════════════════════════

class VisionPresenceDetector:
    """Main presence detection engine combining all vision subsystems.

    Orchestrates camera capture, motion detection, face recognition,
    and gesture recognition into a unified presence detection pipeline.
    """

    def __init__(
        self,
        camera_index: int = 0,
        detection_interval: float = 1.0,
        absence_threshold: float = 30.0,
        on_event: Optional[Callable[[PresenceEvent], None]] = None,
    ):
        self.camera = CameraManager(camera_index=camera_index)
        self.frame_processor = FrameProcessor()
        self.motion_detector = MotionDetector()
        self.face_recognizer = FaceRecognizer()
        self.gesture_recognizer = GestureRecognizer()
        self.lockdown = LockdownManager()

        self.detection_interval = detection_interval
        self.absence_threshold = absence_threshold
        self._on_event = on_event

        self._current_state = PresenceState.UNKNOWN
        self._last_presence_time = 0.0
        self._is_running = False
        self._worker_thread: Optional[threading.Thread] = None
        self._event_history: deque = deque(maxlen=500)
        self._lock = threading.Lock()
        logger.info("VisionPresenceDetector initialized")

    def start(self) -> bool:
        """Start the presence detection pipeline."""
        if not self.camera.open():
            logger.error("Failed to open camera")
            return False
        self._is_running = True
        self._worker_thread = threading.Thread(target=self._detection_loop, daemon=True)
        self._worker_thread.start()
        logger.info("Presence detection started")
        return True

    def stop(self) -> None:
        """Stop the presence detection pipeline."""
        self._is_running = False
        if self._worker_thread:
            self._worker_thread.join(timeout=5.0)
        self.camera.close()
        logger.info("Presence detection stopped")

    def _detection_loop(self) -> None:
        """Main detection loop running in background thread."""
        while self._is_running:
            try:
                frame = self.camera.read_frame()
                if frame is None:
                    time.sleep(0.1)
                    continue

                # Process frame
                processed = self.frame_processor.preprocess(frame)

                # Detect motion
                motion, motion_level, motion_regions = self.motion_detector.process_frame(processed)

                # Face recognition
                faces = self.face_recognizer.recognize_faces(processed)

                # Determine presence state
                old_state = self._current_state
                new_state = self._determine_state(motion, faces)

                if new_state != old_state:
                    event = PresenceEvent(
                        event_type=self._get_event_type(old_state, new_state),
                        state_before=old_state,
                        state_after=new_state,
                        face_count=len(faces),
                        recognized_users=[name for _, name, _ in faces if name],
                        unknown_faces=sum(1 for _, name, _ in faces if name is None),
                        bounding_boxes=[box for box, _, _ in faces],
                        frame_hash=self.frame_processor.compute_frame_hash(processed),
                    )
                    self._emit_event(event)

                with self._lock:
                    self._current_state = new_state

                if new_state == PresenceState.PRESENT:
                    self._last_presence_time = time.time()

                # Check absence timeout
                if (new_state != PresenceState.PRESENT and
                    self._last_presence_time > 0 and
                    time.time() - self._last_presence_time > self.absence_threshold):
                    if self._current_state != PresenceState.ABSENT:
                        with self._lock:
                            self._current_state = PresenceState.ABSENT
                        event = PresenceEvent(
                            event_type="timeout_absent",
                            state_before=old_state,
                            state_after=PresenceState.ABSENT,
                        )
                        self._emit_event(event)

                time.sleep(self.detection_interval)

            except Exception as e:
                logger.error(f"Detection loop error: {e}")
                time.sleep(1.0)

    def _determine_state(self, motion: bool, faces: List[Tuple]) -> PresenceState:
        """Determine presence state from detection results."""
        if not faces and not motion:
            return self._current_state  # No change without evidence

        recognized = [name for _, name, _ in faces if name]
        unknown = sum(1 for _, name, _ in faces if name is None)

        if recognized and unknown == 0:
            return PresenceState.PRESENT
        elif unknown > 0 and not recognized:
            return PresenceState.UNAUTHORIZED
        elif recognized and unknown > 0:
            return PresenceState.MULTIPLE
        elif motion:
            return PresenceState.TRANSITIONING
        return self._current_state

    def _get_event_type(self, old: PresenceState, new: PresenceState) -> str:
        if new == PresenceState.PRESENT and old != PresenceState.PRESENT:
            return "entered"
        elif new == PresenceState.ABSENT:
            return "left"
        elif new == PresenceState.UNAUTHORIZED:
            return "unauthorized"
        elif new == PresenceState.MULTIPLE:
            return "multiple_detected"
        return "state_change"

    def _emit_event(self, event: PresenceEvent) -> None:
        """Emit a presence event to handlers."""
        self._event_history.append(event)
        self.lockdown.on_presence_event(event)
        if self._on_event:
            try:
                self._on_event(event)
            except Exception as e:
                logger.error(f"Presence event callback error: {e}")

    @property
    def current_state(self) -> PresenceState:
        with self._lock:
            return self._current_state

    @property
    def is_running(self) -> bool:
        return self._is_running

    def get_status(self) -> Dict[str, Any]:
        return {
            "is_running": self._is_running,
            "current_state": self._current_state.value,
            "camera_state": self.camera.state.value,
            "frames_processed": self.camera.frame_count,
            "lockdown": self.lockdown.get_status(),
            "motion": self.motion_detector.get_motion_summary(),
            "face_recognizer": self.face_recognizer.stats,
            "event_count": len(self._event_history),
        }

    def get_recent_events(self, limit: int = 20) -> List[Dict[str, Any]]:
        return [e.to_dict() for e in list(self._event_history)[-limit:]]


# ═══════════════════════════════════════════════════════════════════════════
# Vision Pipeline (Unified)
# ═══════════════════════════════════════════════════════════════════════════

class VisionPipeline:
    """High-level vision pipeline combining all detection subsystems.

    Provides a single entry point for frame processing that outputs
    structured detection results from all active analyzers.
    """

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        config = config or {}
        self.presence = VisionPresenceDetector(
            camera_index=config.get("camera_index", 0),
            detection_interval=config.get("detection_interval", 1.0),
        )
        self._analyzers: List[Callable] = []
        self._is_active = False

    def add_analyzer(self, analyzer: Callable) -> None:
        self._analyzers.append(analyzer)

    def start(self) -> bool:
        self._is_active = True
        return self.presence.start()

    def stop(self) -> None:
        self._is_active = False
        self.presence.stop()

    def get_full_status(self) -> Dict[str, Any]:
        return {
            "pipeline_active": self._is_active,
            "analyzers": len(self._analyzers),
            "presence": self.presence.get_status(),
        }
